--------------
-- TABLE 1 --
--------------

CREATE TABLE whatdoyoumean_table (
  Entity VARCHAR(255) NOT NULL,
  Year INTEGER NOT NULL,
  A_<5_YO VARCHAR NOT NULL,
  D_<5_YO VARCHAR NOT NULL,
  A_5-14_YO VARCHAR NOT NULL,
  D_5-14_YO VARCHAR NOT NULL,
  A_15-49_YO VARCHAR NOT NULL,
  D_15-49_YO VARCHAR NOT NULL,
  D_50-69_YO VARCHAR NOT NULL,
  A_50-69_YO VARCHAR NOT NULL,
  A_70+_YO VARCHAR NOT NULL,
  D_70+_YO VARCHAR NOT NULL,
  latitude VARCHAR NOT NULL,
  longitude VARCHAR NOT NULL
);

